M48
; DRILL file {KiCad (7.0.0)} date Thu Jul 13 15:07:22 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-13T15:07:22+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X156.02Y-52.72
X156.03Y-98.23
X191.47Y-52.78
X191.48Y-98.23
T0
M30
